---
- name: Configure my Debian system
  hosts: 127.0.0.1
  connection: local
  become: yes

  roles:
    - shell
    - python
    - editor
    - docker
    # TODO: Ansible
    # TODO: Node
    # TODO: Molecule
    # TODO: Markdown
    # TODO: ZSH
    # TODO: Rust
