---

- name: Configure my Debian system
  hosts: 127.0.0.1
  connection: local
  become: yes

  roles:
    - python
    - molecule
    - gnome
    - editor
    - zsh
    - go
    - rust
    - javascript
    - typescript